language: node_js
node_js:
- '4.1'
before_install:
- npm install -g tsd
deploy:
  provider: npm
  email: npm@smart-coordination.com
  api_key:
    secure: Otp9t0Nb23QQMl3qv4OHx/uARABUHMBqtyfdt+p3jPRvRriWwD7Wytmvoz8+pBYfBBxbSqL2+Jd1E1nT0V+eUHRJm7cmdd3r4kdpOUBD68VQiPjs/ZbX4X+444M7pl5C+UnJpltncqjKAo5HHq5x68w2nOtZoeemJ85IpvVsh02RKLf0Yjl6qXtpECQCPtuq5UR2d25zm9wGeHnSnsgxDKH8U6hslGHzntgIvRYhCiV24j+OQtRsQFtN6XRZMrV0RIs54NO+mYiuzCY3+Sc4QfxEA1QSMZJdL0V6pKs44xdzVOaRWdn11nLMA64hSnSA7qxOAIqVvDERiPfJOy8Fw+0j4GdFU04MQ4PV/8K4wqh0LeWBF/DRU8rhKtL1GscmMtDX/YJvw2DIvanyT3OLxwag1IvbUDUJo+ptA0/6fYlQxn3tjEa8xu2FQ7dYpTZ+FfwOX+pY7H4Jb7/k8T96ptYet8VZg+t8IWyBJ7X64c/EIEC3d/4QhSZrQReM7TrIbNo/66qe2ddFN+kSQ4d+9whGtwaeXGzIjWB4IfYpw8BxEJEGaiBmiJQVidkIQhnTZZMtcX5crb0IU9YEBN1CAE09mDCJP6xvuUhCPy1hbrF/xgYG7rE8auPA3oiQQdjoGsuTDQB+TMEtVL5QTyk/IRsJyvaI4QpsIV29Ox/2zSc=
  on:
    tags: true
    repo: pushrocks/debugsmart
notifications:
  slack:
    secure: f5Uss0z9RPl/QcA/DroB8loyE93aOYI6bqCkrsiUscmZtlv/TVQtT4dxqGA6uvcG6iTQDBi3Ul88dQxWkRm4IqbhY35/iMaV2dHW4FVYMAh8GQMbsfL2sALCcufxD9blw47awv3iFcwhV1EeyesscjgL0JIjduk96v/7G/6QIO2838M1lzlgtj+kRUkim8qkaEs1je3gRrhMUIjLuAdscMXyUKYFMjWo9ACSjVUl30R/ZNemb18itIja6i92GotreBgcfEMczvy58ovDC7xdJUsY8LjMI01DwY+WPRnI0tAhsuI8moBwwcdM4e3bAjKjucQRjO33O5bMWRZ6QCiYd0DnCEFyCPQLJ4GSy/tkD00n8ijLHAOSV3AH1zNbdK1EAdSPQXDvlI36KJn/2hyQLoitGHVUPr76ujJWP82ypO2tgIp3XQU0dJVCxDuHnwJO2+hjdI+gCPqxNTpjeujHx3UdkTGNRjuuf9dlZ/D08fApjYxy2fxItTqo3QjP/nrqvBXUOPP8yPHpjIT4H2t5Pr4SJjBGI6X4qhKyFj6s9rA/Xu1rL+45zu1C3uC3z+u3T9UwrbzJ/cZM6r6UQvQmUvIfBNaMlg4I/diQCDIPL+Rhop2nylY3IcHmJnk2itn7kOqj1tohCpFEml5pRuSZy4udWywkdtyBAsHWFLF7oiQ=
